version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build_and_test: 
    executor: node/default
    steps:
      - checkout # alias for git clone
      - node/install-packages:
          pkg-manager: npm@5
      - run:
          name: Run tests
          command: npm run test
workflows:
  build_test_deploy: # this can be any name you choose
    jobs:
      - build_and_test