version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  build_and_test: 
    steps:
      - checkout # alias for git clone
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install npm dependencies 
          command: npm install --save
      - run:
          name: Run tests
          command: npm run coverage
workflows:
  build_test_deploy: # this can be any name you choose
    jobs:
      - build_and_test
