version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  build_and_test: 
    executor: node/default # use the default executor defined within the orb
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
        name: update npm
        command: npm install -g npm@latest
      - run:
        name: install npm packages
        command: npm install
      - run:
          name: Run tests
          command: npm run test
      # - run:
      #     command: npm run build
      #     name: Build app
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  build_test_deploy: # this can be any name you choose
    jobs:
      - build_and_test
